"""
Agent configurations for 100-agent island simulation with economic inequality.

Distribution:
- 50 agents: Lower Middle Class (Sunset Apartments)
- 25 agents: Middle Class (Coral Village)
- 15 agents: Upper Middle Class (Palm Heights)
- 7 agents: Upper Class (Ocean View Estates)
- 3 agents: Elite (Paradise Point Mansions)
"""

from sim.agents import AgentConfig, ScheduleBias

# === LOWER MIDDLE CLASS - SUNSET APARTMENTS (50 agents) ===

SUNSET_APARTMENTS_AGENTS = [
    # Service workers
    AgentConfig(
        name="Maria Santos",
        home_place="sunset_apartments",
        work_place="cafe",
        personality="Hardworking and cheerful, always has a smile for customers",
        backstory="Moved to the island five years ago seeking a fresh start. Works as a barista at Sunrise Cafe.",
        schedule_bias=ScheduleBias.EARLY_BIRD,
    ),
    AgentConfig(
        name="David Chen",
        home_place="sunset_apartments",
        work_place="general_store",
        personality="Diligent and detail-oriented, takes pride in organizing shelves",
        backstory="Stock clerk at the general store, dreams of opening his own business someday.",
        schedule_bias=ScheduleBias.NINE_TO_FIVE,
    ),
    AgentConfig(
        name="Lisa Martinez",
        home_place="sunset_apartments",
        work_place="clinic",
        personality="Compassionate and patient, genuinely cares about helping others",
        backstory="Nursing assistant at the clinic, studying to become a registered nurse.",
        schedule_bias=ScheduleBias.NINE_TO_FIVE,
    ),
    AgentConfig(
        name="James Wilson",
        home_place="sunset_apartments",
        work_place="harbor",
        personality="Strong and reliable, man of few words but solid work ethic",
        backstory="Dock worker at the harbor, loading and unloading cargo from the ferry.",
        schedule_bias=ScheduleBias.EARLY_BIRD,
    ),
    AgentConfig(
        name="Sophie Brown",
        home_place="sunset_apartments",
        work_place="market",
        personality="Energetic and talkative, loves meeting new people",
        backstory="Market vendor selling fresh flowers and local honey.",
        schedule_bias=ScheduleBias.EARLY_BIRD,
    ),
    AgentConfig(
        name="Marcus Johnson",
        home_place="sunset_apartments",
        work_place="gym",
        personality="Motivating and upbeat, pushes people to reach their potential",
        backstory="Fitness instructor leading morning classes and personal training sessions.",
        schedule_bias=ScheduleBias.EARLY_BIRD,
    ),
    AgentConfig(
        name="Emma Rodriguez",
        home_place="sunset_apartments",
        work_place="restaurant",
        personality="Fast-paced and efficient, thrives under pressure",
        backstory="Waitress at The Island Table, working double shifts to save money.",
        schedule_bias=ScheduleBias.FLEXIBLE,
    ),
    AgentConfig(
        name="Tyler Anderson",
        home_place="sunset_apartments",
        work_place="marina",
        personality="Easygoing and skilled with boats, loves being on the water",
        backstory="Marina attendant managing boat rentals and maintenance.",
        schedule_bias=ScheduleBias.NINE_TO_FIVE,
    ),
    AgentConfig(
        name="Nina Patel",
        home_place="sunset_apartments",
        work_place="cafe",
        personality="Artistic and quiet, expresses herself through latte art",
        backstory="Barista and aspiring artist, decorates drinks with intricate designs.",
        schedule_bias=ScheduleBias.EARLY_BIRD,
    ),
    AgentConfig(
        name="Carlos Garcia",
        home_place="sunset_apartments",
        work_place="market",
        personality="Jovial and haggling expert, makes shopping entertaining",
        backstory="Market vendor specializing in fresh fish and seafood.",
        schedule_bias=ScheduleBias.EARLY_BIRD,
    ),
    AgentConfig(
        name="Rachel Kim",
        home_place="sunset_apartments",
        work_place="library",
        personality="Organized and bookish, passionate about literacy",
        backstory="Library assistant helping with children's reading programs.",
        schedule_bias=ScheduleBias.NINE_TO_FIVE,
    ),
    AgentConfig(
        name="Derek Foster",
        home_place="sunset_apartments",
        work_place="workshop",
        personality="Practical and handy, can fix almost anything",
        backstory="Apprentice woodworker learning traditional crafts.",
        schedule_bias=ScheduleBias.NINE_TO_FIVE,
    ),
    AgentConfig(
        name="Olivia Thompson",
        home_place="sunset_apartments",
        work_place="general_store",
        personality="Friendly and gossipy, knows everyone's business",
        backstory="Cashier at the general store, fountain of island news.",
        schedule_bias=ScheduleBias.FLEXIBLE,
    ),
    AgentConfig(
        name="Ryan Murphy",
        home_place="sunset_apartments",
        work_place="tavern",
        personality="Laid-back and humorous, keeps the atmosphere light",
        backstory="Bartender at The Driftwood Tavern, aspiring comedian.",
        schedule_bias=ScheduleBias.NIGHT_OWL,
    ),
    AgentConfig(
        name="Jessica Lee",
        home_place="sunset_apartments",
        work_place="clinic",
        personality="Calm and methodical, excellent in emergencies",
        backstory="Medical receptionist coordinating appointments and records.",
        schedule_bias=ScheduleBias.NINE_TO_FIVE,
    ),
    AgentConfig(
        name="Andre Washington",
        home_place="sunset_apartments",
        work_place="harbor",
        personality="Weathered and experienced, former fisherman",
        backstory="Harbor maintenance worker, knows every boat and sailor.",
        schedule_bias=ScheduleBias.EARLY_BIRD,
    ),
    AgentConfig(
        name="Samantha Price",
        home_place="sunset_apartments",
        work_place="school",
        personality="Patient and nurturing, natural teacher",
        backstory="Teacher's aide working with elementary students.",
        schedule_bias=ScheduleBias.NINE_TO_FIVE,
    ),
    AgentConfig(
        name="Kevin O'Brien",
        home_place="sunset_apartments",
        work_place="gym",
        personality="Disciplined and fitness-focused, early riser",
        backstory="Gym attendant and personal trainer building his client base.",
        schedule_bias=ScheduleBias.EARLY_BIRD,
    ),
    AgentConfig(
        name="Michelle Torres",
        home_place="sunset_apartments",
        work_place="restaurant",
        personality="Perfectionist and stressed, works too hard",
        backstory="Line cook at The Island Table, dreams of becoming head chef.",
        schedule_bias=ScheduleBias.FLEXIBLE,
    ),
    AgentConfig(
        name="Brandon Hall",
        home_place="sunset_apartments",
        work_place="marina",
        personality="Adventurous and reckless, loves water sports",
        backstory="Boat rental clerk and diving instructor.",
        schedule_bias=ScheduleBias.FLEXIBLE,
    ),
    AgentConfig(
        name="Amanda Wright",
        home_place="sunset_apartments",
        work_place="market",
        personality="Warm and maternal, treats customers like family",
        backstory="Fruit and vegetable vendor, grows some produce herself.",
        schedule_bias=ScheduleBias.EARLY_BIRD,
    ),
    AgentConfig(
        name="Justin Cooper",
        home_place="sunset_apartments",
        work_place="general_store",
        personality="Ambitious and eager, wants to climb the ladder",
        backstory="Assistant manager learning retail operations.",
        schedule_bias=ScheduleBias.NINE_TO_FIVE,
    ),
    AgentConfig(
        name="Natalie Rivera",
        home_place="sunset_apartments",
        work_place="cafe",
        personality="Bubbly and social, remembers everyone's orders",
        backstory="Part-time barista and college student studying online.",
        schedule_bias=ScheduleBias.FLEXIBLE,
    ),
    AgentConfig(
        name="Chris Morgan",
        home_place="sunset_apartments",
        work_place="workshop",
        personality="Creative and meticulous, passionate about craftsmanship",
        backstory="Potter creating functional and decorative ceramics.",
        schedule_bias=ScheduleBias.NINE_TO_FIVE,
    ),
    AgentConfig(
        name="Laura Bell",
        home_place="sunset_apartments",
        work_place="library",
        personality="Introverted and studious, loves quiet spaces",
        backstory="Part-time librarian cataloging and shelving books.",
        schedule_bias=ScheduleBias.NINE_TO_FIVE,
    ),
    AgentConfig(
        name="Daniel Reed",
        home_place="sunset_apartments",
        work_place="harbor",
        personality="Rough around the edges but reliable",
        backstory="Deckhand on fishing boats, does odd jobs at the harbor.",
        schedule_bias=ScheduleBias.EARLY_BIRD,
    ),
    AgentConfig(
        name="Ashley Brooks",
        home_place="sunset_apartments",
        work_place="tavern",
        personality="Flirty and fun, life of the party",
        backstory="Server at the tavern, knows all the island gossip.",
        schedule_bias=ScheduleBias.NIGHT_OWL,
    ),
    AgentConfig(
        name="Jason Scott",
        home_place="sunset_apartments",
        work_place="gym",
        personality="Quiet and focused, leads by example",
        backstory="Gym janitor and equipment maintenance, works out religiously.",
        schedule_bias=ScheduleBias.EARLY_BIRD,
    ),
    AgentConfig(
        name="Melissa Green",
        home_place="sunset_apartments",
        work_place="restaurant",
        personality="Anxious but capable, overthinks everything",
        backstory="Dishwasher and prep cook, very reliable worker.",
        schedule_bias=ScheduleBias.FLEXIBLE,
    ),
    AgentConfig(
        name="Robert Turner",
        home_place="sunset_apartments",
        work_place="market",
        personality="Gruff but fair, no-nonsense attitude",
        backstory="Meat and fish vendor, tough negotiator.",
        schedule_bias=ScheduleBias.EARLY_BIRD,
    ),
    AgentConfig(
        name="Jennifer Adams",
        home_place="sunset_apartments",
        work_place="school",
        personality="Energetic and creative, loves working with kids",
        backstory="Art teacher for after-school programs.",
        schedule_bias=ScheduleBias.NINE_TO_FIVE,
    ),
    AgentConfig(
        name="Michael Phillips",
        home_place="sunset_apartments",
        work_place="marina",
        personality="Methodical and safety-conscious",
        backstory="Marina safety officer and boat inspector.",
        schedule_bias=ScheduleBias.NINE_TO_FIVE,
    ),
    AgentConfig(
        name="Sarah Campbell",
        home_place="sunset_apartments",
        work_place="clinic",
        personality="Empathetic and gentle, wonderful bedside manner",
        backstory="Home health aide visiting elderly residents.",
        schedule_bias=ScheduleBias.FLEXIBLE,
    ),
    AgentConfig(
        name="Matthew Evans",
        home_place="sunset_apartments",
        work_place="general_store",
        personality="Tech-savvy and modern, always on his phone",
        backstory="Delivery driver for the general store.",
        schedule_bias=ScheduleBias.FLEXIBLE,
    ),
    AgentConfig(
        name="Emily Parker",
        home_place="sunset_apartments",
        work_place="cafe",
        personality="Sweet and shy, speaks softly",
        backstory="Baker preparing pastries and bread for the cafe.",
        schedule_bias=ScheduleBias.EARLY_BIRD,
    ),
    AgentConfig(
        name="Joshua Collins",
        home_place="sunset_apartments",
        work_place="harbor",
        personality="Boisterous and storytelling, former sailor",
        backstory="Retired from commercial fishing, now works part-time.",
        schedule_bias=ScheduleBias.EARLY_BIRD,
    ),
    AgentConfig(
        name="Rebecca Stewart",
        home_place="sunset_apartments",
        work_place="library",
        personality="Wise and patient, loves helping people learn",
        backstory="Literacy tutor for adults learning to read.",
        schedule_bias=ScheduleBias.FLEXIBLE,
    ),
    AgentConfig(
        name="Nicholas Morris",
        home_place="sunset_apartments",
        work_place="workshop",
        personality="Talented and underappreciated, skilled metalworker",
        backstory="Blacksmith creating tools and decorative ironwork.",
        schedule_bias=ScheduleBias.NINE_TO_FIVE,
    ),
    AgentConfig(
        name="Stephanie Rogers",
        home_place="sunset_apartments",
        work_place="market",
        personality="Organized and efficient, runs a tight stall",
        backstory="Spice and dry goods vendor with exotic imports.",
        schedule_bias=ScheduleBias.NINE_TO_FIVE,
    ),
    AgentConfig(
        name="Jacob Peterson",
        home_place="sunset_apartments",
        work_place="tavern",
        personality="Philosophical and deep, tends to ramble",
        backstory="Night shift bartender, aspiring writer.",
        schedule_bias=ScheduleBias.NIGHT_OWL,
    ),
    AgentConfig(
        name="Hannah Bailey",
        home_place="sunset_apartments",
        work_place="restaurant",
        personality="Ambitious and competitive, wants recognition",
        backstory="Sous chef working her way up the kitchen hierarchy.",
        schedule_bias=ScheduleBias.FLEXIBLE,
    ),
    AgentConfig(
        name="Ethan Richardson",
        home_place="sunset_apartments",
        work_place="gym",
        personality="Positive and encouraging, former athlete",
        backstory="Group fitness instructor specializing in HIIT.",
        schedule_bias=ScheduleBias.EARLY_BIRD,
    ),
    AgentConfig(
        name="Alexis Cox",
        home_place="sunset_apartments",
        work_place="school",
        personality="Structured and by-the-book, loves routines",
        backstory="Administrative assistant at the community school.",
        schedule_bias=ScheduleBias.NINE_TO_FIVE,
    ),
    AgentConfig(
        name="Gregory Howard",
        home_place="sunset_apartments",
        work_place="marina",
        personality="Knowledgeable and helpful, boat enthusiast",
        backstory="Marina guide offering boat tours and fishing charters.",
        schedule_bias=ScheduleBias.FLEXIBLE,
    ),
    AgentConfig(
        name="Victoria Ward",
        home_place="sunset_apartments",
        work_place="general_store",
        personality="No-nonsense and practical, efficient worker",
        backstory="Night shift stocker, keeps shelves full.",
        schedule_bias=ScheduleBias.NIGHT_OWL,
    ),
    AgentConfig(
        name="Benjamin Torres",
        home_place="sunset_apartments",
        work_place="cafe",
        personality="Hipster and particular about coffee quality",
        backstory="Specialty coffee roaster and barista.",
        schedule_bias=ScheduleBias.NINE_TO_FIVE,
    ),
    AgentConfig(
        name="Megan Hughes",
        home_place="sunset_apartments",
        work_place="clinic",
        personality="Detail-oriented and thorough, catches errors",
        backstory="Medical billing specialist working remotely.",
        schedule_bias=ScheduleBias.FLEXIBLE,
    ),
    AgentConfig(
        name="Samuel Bennett",
        home_place="sunset_apartments",
        work_place="harbor",
        personality="Weathered and salty, seen it all",
        backstory="Harbor master's assistant managing dock assignments.",
        schedule_bias=ScheduleBias.EARLY_BIRD,
    ),
    AgentConfig(
        name="Catherine Wood",
        home_place="sunset_apartments",
        work_place="market",
        personality="Cheerful and religious, sees good in everyone",
        backstory="Baked goods vendor, active in church community.",
        schedule_bias=ScheduleBias.EARLY_BIRD,
    ),
    AgentConfig(
        name="Aaron Long",
        home_place="sunset_apartments",
        work_place="workshop",
        personality="Experimental and innovative, tries new techniques",
        backstory="Jewelry maker creating pieces from sea glass and shells.",
        schedule_bias=ScheduleBias.FLEXIBLE,
    ),
]

# === MIDDLE CLASS - CORAL VILLAGE (25 agents) ===

CORAL_VILLAGE_AGENTS = [
    # Coral Village North (13 agents)
    AgentConfig(
        name="Patricia Henderson",
        home_place="coral_village_1",
        work_place="school",
        personality="Dedicated and caring, treats students like her own children",
        backstory="Elementary school teacher with 15 years experience.",
        schedule_bias=ScheduleBias.NINE_TO_FIVE,
    ),
    AgentConfig(
        name="Thomas Bradley",
        home_place="coral_village_1",
        work_place="town_hall",
        personality="Bureaucratic and procedural, follows all rules",
        backstory="Town clerk managing permits and records.",
        schedule_bias=ScheduleBias.NINE_TO_FIVE,
    ),
    AgentConfig(
        name="Karen Mitchell",
        home_place="coral_village_1",
        work_place="clinic",
        personality="Professional and competent, highly skilled nurse",
        backstory="Registered nurse handling urgent care cases.",
        schedule_bias=ScheduleBias.FLEXIBLE,
    ),
    AgentConfig(
        name="Steven Gray",
        home_place="coral_village_1",
        work_place="general_store",
        personality="Business-minded and strategic, profit-focused",
        backstory="General store manager, part owner of the business.",
        schedule_bias=ScheduleBias.NINE_TO_FIVE,
    ),
    AgentConfig(
        name="Linda Russell",
        home_place="coral_village_1",
        work_place="library",
        personality="Intellectual and cultured, well-read and articulate",
        backstory="Head librarian and community education coordinator.",
        schedule_bias=ScheduleBias.NINE_TO_FIVE,
    ),
    AgentConfig(
        name="Donald Griffin",
        home_place="coral_village_1",
        work_place="harbor",
        personality="Experienced and authoritative, natural leader",
        backstory="Harbor master overseeing all dock operations.",
        schedule_bias=ScheduleBias.EARLY_BIRD,
    ),
    AgentConfig(
        name="Barbara Diaz",
        home_place="coral_village_1",
        work_place="restaurant",
        personality="Passionate about food, perfectionist chef",
        backstory="Head chef at The Island Table, trained in culinary school.",
        schedule_bias=ScheduleBias.FLEXIBLE,
    ),
    AgentConfig(
        name="Paul Hayes",
        home_place="coral_village_1",
        work_place="workshop",
        personality="Master craftsman, traditional and skilled",
        backstory="Furniture maker running the artisan workshop.",
        schedule_bias=ScheduleBias.NINE_TO_FIVE,
    ),
    AgentConfig(
        name="Susan Chavez",
        home_place="coral_village_1",
        work_place="school",
        personality="Strict but fair, high academic standards",
        backstory="Middle school math and science teacher.",
        schedule_bias=ScheduleBias.NINE_TO_FIVE,
    ),
    AgentConfig(
        name="Richard Webb",
        home_place="coral_village_1",
        work_place="marina",
        personality="Adventurous and experienced, loves the ocean",
        backstory="Marina manager and certified sailing instructor.",
        schedule_bias=ScheduleBias.FLEXIBLE,
    ),
    AgentConfig(
        name="Nancy Simpson",
        home_place="coral_village_1",
        work_place="town_hall",
        personality="Diplomatic and tactful, good with people",
        backstory="Community relations coordinator for town hall.",
        schedule_bias=ScheduleBias.NINE_TO_FIVE,
    ),
    AgentConfig(
        name="Charles Porter",
        home_place="coral_village_1",
        work_place="gym",
        personality="Health-conscious and disciplined, leads by example",
        backstory="Gym owner and head fitness coach.",
        schedule_bias=ScheduleBias.EARLY_BIRD,
    ),
    AgentConfig(
        name="Donna Freeman",
        home_place="coral_village_1",
        work_place="cafe",
        personality="Entrepreneurial and creative, always innovating",
        backstory="Cafe owner creating seasonal menus and specials.",
        schedule_bias=ScheduleBias.EARLY_BIRD,
    ),

    # Coral Village South (12 agents)
    AgentConfig(
        name="Frank Stevens",
        home_place="coral_village_2",
        work_place="market",
        personality="Savvy businessman, shrewd negotiator",
        backstory="Market coordinator managing vendor relations.",
        schedule_bias=ScheduleBias.EARLY_BIRD,
    ),
    AgentConfig(
        name="Helen Butler",
        home_place="coral_village_2",
        work_place="clinic",
        personality="Experienced and knowledgeable, mentors younger staff",
        backstory="Senior nurse practitioner, island resident for 20 years.",
        schedule_bias=ScheduleBias.NINE_TO_FIVE,
    ),
    AgentConfig(
        name="George Coleman",
        home_place="coral_village_2",
        work_place="tavern",
        personality="Gregarious and welcoming, knows everyone",
        backstory="Tavern owner, central figure in island social life.",
        schedule_bias=ScheduleBias.NIGHT_OWL,
    ),
    AgentConfig(
        name="Dorothy Jenkins",
        home_place="coral_village_2",
        work_place="school",
        personality="Nurturing and patient, wonderful with children",
        backstory="Kindergarten teacher beloved by students and parents.",
        schedule_bias=ScheduleBias.NINE_TO_FIVE,
    ),
    AgentConfig(
        name="Kenneth Perry",
        home_place="coral_village_2",
        work_place="harbor",
        personality="Skilled mechanic, can fix any engine",
        backstory="Lead boat mechanic and repair specialist.",
        schedule_bias=ScheduleBias.NINE_TO_FIVE,
    ),
    AgentConfig(
        name="Margaret Powell",
        home_place="coral_village_2",
        work_place="library",
        personality="Creative and literary, runs book clubs",
        backstory="Assistant librarian and local book author.",
        schedule_bias=ScheduleBias.FLEXIBLE,
    ),
    AgentConfig(
        name="Arthur Ross",
        home_place="coral_village_2",
        work_place="workshop",
        personality="Artistic and visionary, pushes boundaries",
        backstory="Sculptor and workshop instructor teaching classes.",
        schedule_bias=ScheduleBias.FLEXIBLE,
    ),
    AgentConfig(
        name="Frances Henderson",
        home_place="coral_village_2",
        work_place="restaurant",
        personality="Elegant and refined, excellent host",
        backstory="Restaurant manager ensuring impeccable service.",
        schedule_bias=ScheduleBias.FLEXIBLE,
    ),
    AgentConfig(
        name="Harold Coleman",
        home_place="coral_village_2",
        work_place="town_hall",
        personality="Political and connected, well-informed",
        backstory="Deputy mayor handling daily administrative duties.",
        schedule_bias=ScheduleBias.NINE_TO_FIVE,
    ),
    AgentConfig(
        name="Evelyn Barnes",
        home_place="coral_village_2",
        work_place="art_gallery",
        personality="Cultured and discerning, eye for talent",
        backstory="Art gallery curator promoting local artists.",
        schedule_bias=ScheduleBias.FLEXIBLE,
    ),
    AgentConfig(
        name="Walter Fisher",
        home_place="coral_village_2",
        work_place="marina",
        personality="Technical and detail-oriented, expert sailor",
        backstory="Yacht maintenance specialist and sailing coach.",
        schedule_bias=ScheduleBias.NINE_TO_FIVE,
    ),
    AgentConfig(
        name="Joyce Vasquez",
        home_place="coral_village_2",
        work_place="gym",
        personality="Motivational and inspiring, fitness evangelist",
        backstory="Yoga and pilates instructor with holistic approach.",
        schedule_bias=ScheduleBias.EARLY_BIRD,
    ),
]

# === UPPER MIDDLE CLASS - PALM HEIGHTS (15 agents) ===

PALM_HEIGHTS_AGENTS = [
    # Palm Heights East (8 agents)
    AgentConfig(
        name="Dr. Elizabeth Montgomery",
        home_place="palm_heights_1",
        work_place="clinic",
        personality="Brilliant and dedicated, workaholic physician",
        backstory="Island's primary care doctor, medical director of the clinic.",
        schedule_bias=ScheduleBias.FLEXIBLE,
    ),
    AgentConfig(
        name="William Caldwell",
        home_place="palm_heights_1",
        work_place="town_hall",
        personality="Charismatic and political, natural leader",
        backstory="Island mayor balancing development with preservation.",
        schedule_bias=ScheduleBias.NINE_TO_FIVE,
    ),
    AgentConfig(
        name="Margaret Thornton",
        home_place="palm_heights_1",
        work_place="school",
        personality="Accomplished and demanding, high expectations",
        backstory="School principal and education reform advocate.",
        schedule_bias=ScheduleBias.NINE_TO_FIVE,
    ),
    AgentConfig(
        name="Robert Ashford",
        home_place="palm_heights_1",
        work_place="restaurant",
        personality="Sophisticated and worldly, cosmopolitan taste",
        backstory="Restaurant owner, formerly ran establishments in major cities.",
        schedule_bias=ScheduleBias.FLEXIBLE,
    ),
    AgentConfig(
        name="Catherine Sinclair",
        home_place="palm_heights_1",
        work_place="art_gallery",
        personality="Refined and artistic, well-traveled collector",
        backstory="Gallery owner with connections to mainland art world.",
        schedule_bias=ScheduleBias.FLEXIBLE,
    ),
    AgentConfig(
        name="James Whitmore",
        home_place="palm_heights_1",
        work_place="harbor",
        personality="Pragmatic and business-savvy, expansion-minded",
        backstory="Harbor development director planning expansion projects.",
        schedule_bias=ScheduleBias.NINE_TO_FIVE,
    ),
    AgentConfig(
        name="Virginia Preston",
        home_place="palm_heights_1",
        work_place="library",
        personality="Intellectual and philanthropic, community benefactor",
        backstory="Library board president and major donor.",
        schedule_bias=ScheduleBias.FLEXIBLE,
    ),
    AgentConfig(
        name="Edward Harrison",
        home_place="palm_heights_1",
        work_place="marina",
        personality="Competitive and status-conscious, avid yachtsman",
        backstory="Private yacht owner and marina board member.",
        schedule_bias=ScheduleBias.FLEXIBLE,
    ),

    # Palm Heights West (7 agents)
    AgentConfig(
        name="Carolyn Beaumont",
        home_place="palm_heights_2",
        work_place="school",
        personality="Progressive and innovative, champions new methods",
        backstory="High school teacher developing advanced curriculum.",
        schedule_bias=ScheduleBias.NINE_TO_FIVE,
    ),
    AgentConfig(
        name="Douglas Pemberton",
        home_place="palm_heights_2",
        work_place="town_hall",
        personality="Strategic and planning-focused, thinks long-term",
        backstory="Town planner overseeing zoning and development.",
        schedule_bias=ScheduleBias.NINE_TO_FIVE,
    ),
    AgentConfig(
        name="Eleanor Fitzgerald",
        home_place="palm_heights_2",
        work_place="restaurant",
        personality="Elegant and social, networking expert",
        backstory="Restaurant partner and event coordinator.",
        schedule_bias=ScheduleBias.FLEXIBLE,
    ),
    AgentConfig(
        name="Victor Aldridge",
        home_place="palm_heights_2",
        work_place="workshop",
        personality="Perfectionist and artistic, internationally recognized",
        backstory="Master craftsman whose work is sold in galleries worldwide.",
        schedule_bias=ScheduleBias.FLEXIBLE,
    ),
    AgentConfig(
        name="Beatrice Wentworth",
        home_place="palm_heights_2",
        work_place="art_gallery",
        personality="Critical and discerning, tastemaker",
        backstory="Art dealer and consultant for private collections.",
        schedule_bias=ScheduleBias.FLEXIBLE,
    ),
    AgentConfig(
        name="Frederick Sterling",
        home_place="palm_heights_2",
        work_place="marina",
        personality="Adventurous and experienced, ocean explorer",
        backstory="Charter captain offering luxury sailing excursions.",
        schedule_bias=ScheduleBias.FLEXIBLE,
    ),
    AgentConfig(
        name="Vivian Lockwood",
        home_place="palm_heights_2",
        work_place="gym",
        personality="Health-conscious and disciplined, wellness advocate",
        backstory="Wellness center owner offering spa and fitness services.",
        schedule_bias=ScheduleBias.EARLY_BIRD,
    ),
]

# === UPPER CLASS - OCEAN VIEW ESTATES (7 agents) ===

OCEAN_VIEW_AGENTS = [
    AgentConfig(
        name="Dr. Jonathan Bancroft",
        home_place="ocean_view_1",
        work_place="clinic",
        personality="Highly educated and reserved, specialist physician",
        backstory="Semi-retired surgeon who consults part-time at the clinic.",
        schedule_bias=ScheduleBias.FLEXIBLE,
    ),
    AgentConfig(
        name="Lillian Hartwell",
        home_place="ocean_view_1",
        work_place="art_gallery",
        personality="Sophisticated and cultured, patron of the arts",
        backstory="Art collector and gallery investor, maintains connections to international auction houses.",
        schedule_bias=ScheduleBias.FLEXIBLE,
    ),
    AgentConfig(
        name="Alexander Kensington",
        home_place="ocean_view_2",
        work_place="marina",
        personality="Aristocratic and traditional, old money values",
        backstory="Retired investment banker, yacht club commodore.",
        schedule_bias=ScheduleBias.FLEXIBLE,
    ),
    AgentConfig(
        name="Isabelle Worthington",
        home_place="ocean_view_2",
        work_place="restaurant",
        personality="Gracious and philanthropic, community leader",
        backstory="Silent partner in several island businesses, active in charity work.",
        schedule_bias=ScheduleBias.FLEXIBLE,
    ),
    AgentConfig(
        name="Montgomery Blackwood",
        home_place="ocean_view_3",
        work_place="town_hall",
        personality="Influential and commanding, used to authority",
        backstory="Former state senator, now island planning commissioner.",
        schedule_bias=ScheduleBias.NINE_TO_FIVE,
    ),
    AgentConfig(
        name="Genevieve Ashbourne",
        home_place="ocean_view_3",
        work_place="library",
        personality="Scholarly and erudite, published author",
        backstory="Retired professor writing historical novels about island history.",
        schedule_bias=ScheduleBias.FLEXIBLE,
    ),
    AgentConfig(
        name="Reginald Fairfax",
        home_place="ocean_view_4",
        work_place="harbor",
        personality="Shrewd and calculating, business magnate",
        backstory="Real estate developer with significant island property holdings.",
        schedule_bias=ScheduleBias.NINE_TO_FIVE,
    ),
]

# === ELITE - PARADISE POINT MANSIONS (3 agents) ===

PARADISE_POINT_AGENTS = [
    AgentConfig(
        name="Maximilian Vanderbilt III",
        home_place="paradise_point_1",
        work_place=None,
        personality="Supremely wealthy and somewhat detached, philanthropist",
        backstory="Heir to shipping fortune, owns private yacht and funds island projects. Rarely works but sits on multiple boards.",
        schedule_bias=ScheduleBias.FLEXIBLE,
    ),
    AgentConfig(
        name="Anastasia Rothschild-Laurent",
        home_place="paradise_point_2",
        work_place="art_gallery",
        personality="Cosmopolitan and elite, international socialite",
        backstory="Art world insider with homes on three continents, curates exclusive exhibitions.",
        schedule_bias=ScheduleBias.FLEXIBLE,
    ),
    AgentConfig(
        name="Sebastian Whitehall-Pembroke",
        home_place="paradise_point_3",
        work_place=None,
        personality="Eccentric and reclusive, tech entrepreneur",
        backstory="Sold software company for billions, now pursues personal interests and marine conservation. Rarely seen in public.",
        schedule_bias=ScheduleBias.NIGHT_OWL,
    ),
]

# === AGGREGATE ALL AGENTS ===

ISLAND_100_AGENTS = (
    SUNSET_APARTMENTS_AGENTS +
    CORAL_VILLAGE_AGENTS +
    PALM_HEIGHTS_AGENTS +
    OCEAN_VIEW_AGENTS +
    PARADISE_POINT_AGENTS
)

# Verify we have exactly 100 agents
assert len(ISLAND_100_AGENTS) == 100, f"Expected 100 agents, got {len(ISLAND_100_AGENTS)}"

# Distribution verification
assert len(SUNSET_APARTMENTS_AGENTS) == 50, f"Expected 50 LMC agents, got {len(SUNSET_APARTMENTS_AGENTS)}"
assert len(CORAL_VILLAGE_AGENTS) == 25, f"Expected 25 MC agents, got {len(CORAL_VILLAGE_AGENTS)}"
assert len(PALM_HEIGHTS_AGENTS) == 15, f"Expected 15 UMC agents, got {len(PALM_HEIGHTS_AGENTS)}"
assert len(OCEAN_VIEW_AGENTS) == 7, f"Expected 7 UC agents, got {len(OCEAN_VIEW_AGENTS)}"
assert len(PARADISE_POINT_AGENTS) == 3, f"Expected 3 Elite agents, got {len(PARADISE_POINT_AGENTS)}"

print(f"✓ Successfully configured {len(ISLAND_100_AGENTS)} agents with economic distribution:")
print(f"  - Lower Middle Class (Sunset Apartments): {len(SUNSET_APARTMENTS_AGENTS)} agents")
print(f"  - Middle Class (Coral Village): {len(CORAL_VILLAGE_AGENTS)} agents")
print(f"  - Upper Middle Class (Palm Heights): {len(PALM_HEIGHTS_AGENTS)} agents")
print(f"  - Upper Class (Ocean View): {len(OCEAN_VIEW_AGENTS)} agents")
print(f"  - Elite (Paradise Point): {len(PARADISE_POINT_AGENTS)} agents")
